# ========================== SERVER ==========================
server.port=8080

# ========================== DATABASE ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/oco_fruit_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mingquan
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA settings (entities)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

recaptcha.secret=6LdKWgUtAAAAANSBnuC0mhzFTcgj9K_oZm6DAojD